name: Download Forge for Akashic Server
# By Myth, created for Akashic Server


on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'


jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    
    - uses: actions/checkout@v2

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Create server folder
      run: mkdir server
    
    - name: Copy Forge Installer
      run: cp forge*.jar server/

    - name: Download Forge files
      run: cd server && java -jar forge*.jar --installServer && rm forge*installer* && cd ..

    - uses: actions/upload-artifact@v2
      with:
        name: Forge-Server
        path: server